## The following lines must be changed
velociraptor_version: 0.6.9
velociraptor_ip: 192.168.56.6
velociraptor_gw: 192.168.56.1
velociraptor_dns: 9.9.9.9
velociraptor_admin_user: admin
velociraptor_admin_password: Sup3rS3cr3t

## Do not change these lines
velociraptor_install_dir: /tmp
velociraptor_server_config: server.config.yaml
velociraptor_client_config: Velociraptor.config.yaml